# Generated by Django 4.2.7 on 2024-02-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suzdalimage',
            name='image5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suzdalimage',
            name='image6',
            field=models.TextField(null=True),
        ),
    ]
