# Generated by Django 4.2.7 on 2024-02-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_suzdaluser_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suzdaluser',
            name='category',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='suzdaluser',
            name='images',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='suzdaluser',
            name='province',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='suzdaluser',
            name='zone',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
